#!/bin/bash

curl -vvv  -H  "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7" -H  "Accept-Encoding: gzip, deflate" -H  "Accept-Language: en-US,en;q=0.9" -H  "Connection: keep-alive" -H  "Host: www.microchip.com" -H  "Upgrade-Insecure-Requests: 1"  -L -A " Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36" "$@"

